### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by calex80** [optiv/Freeze#8]
I am getting this error. Please help

![image](https://user-images.githubusercontent.com/58860205/231013164-554e6840-ab7f-4899-aece-7fbbec9b9092.png)

**Comment by Tylous** [comment]
What version of Golang do you have?

**Comment by calex80** [comment]
I have go1.20.3

**Comment by Tylous** [comment]
Use go1.19.x as there are some issues with go.1.20.x  with garble@v0.7.2

**Comment by calex80** [comment]
Thank you, I will do

**Comment by calex80** [comment]
I am facing trouble installing garble with go 1.19, it says 1.20 or higher is required. Any help?

**Comment by HopHouse** [comment]
Hello, 
In order to make it works, you must update the garble version.

**Comment by Tylous** [comment]
This has been fixed in the latest version I just released.
